### DISCUSSION TITLE
Rendered prompt does not show equivalent JSON payload when calling OpenAI API directly

### DISCUSSION THREAD

**Discussion by vicperdana** [microsoft/semantic-kernel#6817] [Q&A] [answered]
Hi, 
When using the handlebar template, it seems that the rendered prompt is different than what's being accepted in OpenAI API directly.  This is our handlebar template and rendered prompt.  

Is the rendered prompt being 'translated' to the acceptable JSON payload before passing to OpenAI?
If, so how do we view the raw request made to OpenAI?

### Handlebar template and resulting rendered prompt
```yaml
name: transcribeScreenshot
description: Extract text from image
template: |
  <message role='user'>
   <text>what is this image</text>
   <image>https://i.imgur.com/1RP78PA.jpeg</image>
  </message>
template_format: handlebars
```
Output:
```
trce: Microsoft.SemanticKernel.KernelFunctionFactory[0]
      Rendered prompt: <message role='user'>
       <text>what is this image</text>
       <image>https://i.imgur.com/1RP78PA.jpeg</image>
      </message>
```
### OpenAI API direct call with Postman
Request
```json
{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "user",
      "content": "<message role='user'><text>what is this image</text><image>https://i.imgur.com/1RP78PA.jpeg</image></message>"
    }
  ]
}
```
Output

```json
{
  "id": "chatcmpl-xxxxx",
  "object": "chat.completion",
  "created": 1718774484,
  "model": "gpt-4o-2024-05-13",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "I'm currently unable to view images directly. However, you can describe the image to me, and I can help provide information or context based on your description!"
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 40,
    "completion_tokens": 31,
    "total_tokens": 71
  },
  "system_fingerprint": "fxxxxx"
}
```
