### DISCUSSION TITLE
How to use auto invoke function calling in YAML prompt

### DISCUSSION THREAD

**Discussion by KishanJ98** [microsoft/semantic-kernel#8706] [Q&A] [answered]
I have a YAML prompt and a GenerateImage KernelFunction which uses Dall-E to generate an image. However I want the SK to determine to call this function based on the intent of the user if it wants to generate an image.
I tried to use this:
```
function_choice_behavior:
              type: auto
              functions:
              - ChatPlugin.GenerateImage
```
This is the code I use to create the KernelFunction from YAML:
```
 var chatPrompt = EmbeddedResource.Read("ChatPrompt.yaml");
 var chatPromptFunction = Kernel.CreateFunctionFromPromptYaml(chatPrompt);
```
But this is not calling the method. If I put this in the prompt: {{ChatPlugin.GenerateImage}}, then the method is called, but it is called everytime regardless of the user wanting to generate an image or not.
Any ideas on how to do make this work?
