### ISSUE TITLE
.Net: New Feature: Support for structured output through Prompty file

### ISSUE THREAD

**Issue by husseinkorly** [microsoft/semantic-kernel#10131]
---
name: Feature request
about: Adding support for structured output through Prompty

---

Currently, we can set the `response_format` property programmatically in code, as shown below:

```c#
var settings = new OpenAIPromptExecutionSettings
{
    MaxTokens = 16384,
    Temperature = 0.0,
    TopP = 0.00,
    PresencePenalty = 0.0,
    FrequencyPenalty = 0.0,
    ResponseFormat = typeof(InvoiceData)
};
```
This configuration ensures that the response from the Large Language Model (LLM) aligns with the specified format (InvoiceData in this example).

Request:
I was wondering, if possible, to do the same through Prompty template for example:

```yml
name: InvoiceDocumentExtraction
description: This prompt is used to extract information from an invoice document.
authors:
  - HK
model:
  api: chat
  configuration:
    type: azure_openai
  parameters:
    max_tokens: 16384
    temperature: 0.0
    top_p: 0.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    response_format: <reference to a file>
```

the file could reference a predefined response format (e.g., InvoiceData class or schema), ensuring consistent structure in the LLM's output. This is particularly useful for tasks like extracting structured data from documents.

I see Prompty support the following
- https://github.com/microsoft/prompty/issues/69
- https://github.com/microsoft/prompty/pull/93
