### ISSUE TITLE
.Net: Bug: Special characters in Handlebars templates cause silent failure

### ISSUE THREAD

**Issue by LuisM000** [microsoft/semantic-kernel#10288]
**Describe the bug**  
When using Handlebars templates with special characters like `&amp;` (&), the output is incorrect. Instead of generating separate chat messages, it combines everything into one single message. 
This issue occurs because the `&amp;` character is transformed into `&` before reaching the XML transformation step, which causes an exception in [XmlPromptParser](https://github.com/microsoft/semantic-kernel/blob/4d29656780a16b0a121163cf88653b041b89e15b/dotnet/src/SemanticKernel.Abstractions/AI/XmlPromptParser.cs#L57). As a result, the process fails without clear feedback or proper exception handling, making it difficult to diagnose the issue.

**To Reproduce**  
1. Define a Handlebars template with special characters like `&amp;`:
   ```yaml
   name: getTimes
   description: Gets the time in various cities.
   template: |
     <message role=""user"">Can you help me tell &amp; the time in Seattle right now?</message>
     <message role=""assistant"">Sure! The time in Seattle is currently 3:00 PM.</message>
     <message role=""user"">What about New York?</message>
   template_format: handlebars
   ```
2. Use this template in the kernel function with `KernelFunctionYaml`.
3. Invoke the function with the template and observe the result.

**Expected behavior**  
This should generate three separate chat messages:
1. `ChatMessageContent user => "Can you help me tell & the time in Seattle right now?"`
2. `ChatMessageContent assistant => "Sure! The time in Seattle is currently 3:00 PM."`
3. `ChatMessageContent user => "What about New York?"`

**Actual behavior**  
The entire content is combined into a single message:
1. `ChatMessageContent user => "<message role="user">Can you help me tell & the time in Seattle right now?</message><message role="assistant">Sure! The time in Seattle is currently 3:00 PM.</message><message role="user">What about New York?</message>"`

**Platform**  
- OS: [Windows]  
- IDE: [Visual Studio]  
- Language: [C#]  
- Source: [NuGet package version 1.34.0]

**Code to reproduce**  
```csharp
var kernel = Kernel.CreateBuilder()
    .AddAzureOpenAIChatCompletion("gpt-4o", "https://xxxxxx.openai.azure.com/", "xxxxxxxx")
    .Build();

const string template = @"
name: getTimes
description: Gets the time in various cities.
template: |
  <message role=""user"">Can you help me tell &amp; the time in Seattle right now?</message>
  <message role=""assistant"">Sure! The time in Seattle is currently 3:00 PM.</message>
  <message role=""user"">What about New York?</message>
template_format: handlebars
";

var kernelFunction = KernelFunctionYaml.FromPromptYaml(template, new HandlebarsPromptTemplateFactory());

var result = await kernel.InvokeAsync(kernelFunction);
```

**Additional context**  
I have tried using `AllowUnsafeContent`, but it does not resolve the problem in this specific case since the `&amp;` is not part of a dynamic variable.

As a workaround, I have to escape the `&` character twice. This is necessary because, during the Handlebars rendering, the result is decoded after the template is rendered (as seen in [this line](https://github.com/microsoft/semantic-kernel/blob/4d29656780a16b0a121163cf88653b041b89e15b/dotnet/src/Extensions/PromptTemplates.Handlebars/HandlebarsPromptTemplate.cs#L54)). If I only escape the `&` once, it gets decoded during this step and would return as `&`, which would then cause the error in the `XmlPromptParser`.
```yaml
name: getTimes
description: Gets the time in various cities.
template: |
  <message role=""user"">Can you help me tell &amp;amp; the time in Seattle right now?</message>
  <message role=""assistant"">Sure! The time in Seattle is currently 3:00 PM.</message>
  <message role=""user"">What about New York?</message>
template_format: handlebars
```
