### ISSUE TITLE
Python: Bug: Python: Incompatibility between yaml response_format and AzureAIInference

### ISSUE THREAD

**Issue by mathrb** [microsoft/semantic-kernel#12290]
**Describe the bug**
Declaring the response_format in a yaml file does not work with AzureAIInference.

**To Reproduce**
Create a yaml function:
```yaml
name: DummyPrompt
description: hello
template_format: jinja2
execution_settings:
  azure_ai_inference:
    max_tokens: 100
    temperature: 0.0
    response_format: 
      type: json_schema
      json_schema:
        name: dummy_format
        schema:
          type: object
          properties:
           message: {type: string}
template: |
  <message role="system">
    Your goal is to return the message of the user as JSON.
  </message>
  <message role="user">
    {{ message }}
  </message>
```
Try to invoke the function with AzureAIInferenceChatCompletion.

SemanticKernel, and more specificaly AzureAIInferenceChatPromptExecutionSettings expects that response_format to be {"type": "json_schema", "json_schema": {}} [link](https://github.com/microsoft/semantic-kernel/blob/079594d29792071c0474dc30543697972b77dbc9/python/semantic_kernel/connectors/ai/azure_ai_inference/azure_ai_inference_prompt_execution_settings.py#L68)
The problem lies in the fact that the response_format is passed directly to [AzureAIInferenceChatCompletion](https://github.com/microsoft/semantic-kernel/blob/079594d29792071c0474dc30543697972b77dbc9/python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_chat_completion.py#L263)
Therefore, the JsonSchemaFormat cannot be created because it contains  {"type": "json_schema", "json_schema": {}} instead of the content of json_schema

**Expected behavior**
The json_schema is correctly passed when read from dict.

**Platform**
 - Language: Python
 - Source: semantic-kernel==1.32.0 azure-ai-inference==1.0.0b9
 - AI model: N/A, the problem arise before actually calling the model

**Additional context**

In the [code](https://github.com/microsoft/semantic-kernel/blob/079594d29792071c0474dc30543697972b77dbc9/python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_chat_completion.py#L261C13-L261C98):
`# Case 4: response_format is a dictionary (legacy), create JsonSchemaFormat from dict`
Does it mean that using YAML isn't intended anymore, or am I missing something?
