### ISSUE TITLE
Python: Bug: AzureAIAgent doesn't register custom functions (plugins) in Azure AI Foundry

### ISSUE THREAD

**Issue by karolzak** [microsoft/semantic-kernel#12492]
**Describe the bug**
When I try to create a new AzureAIAgent with some custom plugins using AgentRegistry.create_from_file it works correctly when invoked in the local context but when I go to Azure AI Foundry, I see it's created correctly but it's missing the custom plugins I created it with.
I tried using different combinations of kernel, plugins and tools definition in yaml and nothing seems to solve this.

**To Reproduce**
Minimum code to reproduce the behavior:
```python
import asyncio

from azure.identity.aio import DefaultAzureCredential

from semantic_kernel.agents import AgentRegistry, AzureAIAgent, AzureAIAgentSettings
from semantic_kernel.kernel import Kernel
from src.tools.calculator import CalculatorPlugin

"""
The following sample demonstrates how to create an Azure AI agent that can serve user as a calculator
using a custom implementation of Semantic Kernel Plugin. The agent is created using a yaml declarative spec.
The agent can perform basic arithmetic operations like addition and multiplication.
"""

# Simulate a conversation with the agent
USER_INPUTS = [
    "Hello",
    "I want to add two numbers, 453 and 789.",
    "Now, multiply the result by 3",
    "Thank you",
]


async def main() -> None:
    settings = AzureAIAgentSettings()
    
    async with (
        DefaultAzureCredential() as creds,
        AzureAIAgent.create_client(credential=creds) as client,
    ):
        # 1. Create a Kernel instance
        # For declarative agents, the kernel is required to resolve the plugin(s)
        kernel = Kernel()
        kernel.add_plugin(CalculatorPlugin())

        # 2. Create a Semantic Kernel agent for the Azure AI agent
        agent: AzureAIAgent = await AgentRegistry.create_from_file(
            "src/agents/declarative/calculator.yaml",
            kernel=kernel,
            # plugins=[CalculatorPlugin()],
            settings=settings,
            client=client
        )

        # 3. Create a thread for the agent
        # If no thread is provided, a new thread will be
        # created and returned with the initial response
        thread = None

        try:
            for user_input in USER_INPUTS:
                print(f"# User: {user_input}")
                # 4. Invoke the agent for the specified thread for response
                async for response in agent.invoke(
                    messages=user_input,
                    thread=thread,
                ):
                    print(f"# {response.name}: {response}")
                    thread = response.thread  
        finally:
            print("# Conversation ended.")
            # 5. Cleanup: Delete the thread and agent
            # await thread.delete() if thread else None
            # await client.agents.delete_agent(agent.id)


if __name__ == "__main__":
    asyncio.run(main())

```

Agent definition in yaml:
```yaml
type: foundry_agent
name: CalculatorAgent
description: This agent uses the provided tools to perform calculations based on user queries.
instructions: Use the provided tools to perform calculations based on user queries.
model:
  id: ${AzureAI:ChatModelId}
  options:
    temperature: 0.4
tools:
  - id: CalculatorPlugin.add_numbers
    type: function
  - id: CalculatorPlugin.subtract_numbers
    type: function
  - id: CalculatorPlugin.multiply_numbers
    type: function
  - id: CalculatorPlugin.divide_numbers
    type: function
  - id: CalculatorPlugin.calculate_percentage
    type: function
  - id: CalculatorPlugin.format_currency
    type: function
```

**Expected behavior**
I would expect AzureAIAgent to correctly register agent in Azure AI Foundry along with custom functions/tools.

**Platform**
 - Language: Python
 - Source: pip package version 3.3.0 (also tried earlier 3.2.1 version)
 - AI model: Azure OpenAI: GPT-4o
 - IDE: VS Code
 - OS: Windows with WSL Ubuntu (+dev container)
