### ISSUE TITLE
python: init ContextVariables from nested dict

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#1257]
When I want to show hierarchical data to GPT, I'm using json as the format, which creates a nested_dictionary.
Currently, ContextVariables doesn't have a classmethod like from_dict that can handle nested dict automatically.

```python
# current SK
context = ContextVariables()
for k, v in nested_dict.items():
    context[k] = json.dumps(v, indent=4)
```

```python
# Feature Request
context = ContextVaraibles.from_dict(nested_dict)
```

**Comment by alexchaomander** [comment]
@joowon-dm-snu would you want the dictionary to stay nested or flattened? Because the prompt will not be nested.

**Comment by joowon-dm-snu** [comment]
It seems like there was a lack of context, so let me give you a simple example. 

I think one of the key functions of a chatbot is to extract the user's intention from their input. 
As the chatbot becomes more advanced, the intents are usually subdivided into a tree structure. 
To handle this conveniently, I typically organize the intent list using YAML. 

Here's an example: 
```yaml
intent_config:
  details:
    STOCK:
      STATUS: 
        description: Gets the current status of individual stocks, including information on open, close, high, low, and more.
        parameters: {"stock_name": str or "None"}
      ANALYZE: 
        description: Brings up analytical reports for individual stocks.
        parameters: {"stock_name": str or "None"}
      ORDER: 
        description: User wants to buy or sell stock. Place an order for an individual stock. 
        parameters: {
          order_type: buy or sell or "None",
          stock_name: str or "None",
          price: price of stock or "None",
          quantity: quantity of stock or "None"
        }
      UNKNOWN: 
        description: Cannot match users intent
        parameters: {}
```

The following defines semantic functions that can extract intents from user with config above. 
```
Your job is to parse [INTENT_TYPE] and [INTENT_PARAMETERS] from [INTENT_DETAILS] and User input.

...

[INTENT_DETAILS]
{{$intent_details}}
[/INTENT_DETAILS]

...

```

In this situation, nested dictionaries can cause errors, so I have to apply `json.dumps` for each context every time. 
Here's an example of the code:
```
class IntentKernel:
    def __init__(self, skill_dir: str, config: Dict, logger=None):
        self._skill_dir = skill_dir
        self._config = config

        self._kernel = build_kernel(logger=logger)
        self._skills = import_skills(self._kernel, skill_dir=skill_dir)

    def _prepare_context(self, chat_history: str, user_input: str):
        context = ContextVariables()
        context["intent_types"] = json.dumps(self._config["types"], indent=4)
        context["intent_details"] = json.dumps(self._config["details"], indent=4)
        context["chat_history"] = chat_history
        context["user_input"] = user_input

        return context

    async def query(self, chat_history: str, user_input: str) -> Dict:
        ctx = self._prepare_context(chat_history, user_input)
        func = self._skills["DetectIntentionSkill"]["ParseIntent"]
        res = await self._kernel.run_async(func, input_vars=ctx)

        return json.loads(res.result.strip())
```

This issue can be seen as a convenience feature rather than an essential function. It helps users immediately convert various configurations or JSON into ContextVariables for immediate use. 

Personally, when dealing with API integration, I often found it cumbersome to handle data in JSON format :)
