### ISSUE TITLE
.Net: Sequential planner uses unknown steps

### ISSUE THREAD

**Issue by rosieks** [microsoft/semantic-kernel#2262]
**Describe the bug**
Exception during creating plan:

>PlanningException: Invalid plan: Failed to find function 'XML.ExtractValue' in skill 'XML'.

**To Reproduce**
I get this exception while running the following code:
```csharp
var kernel = new KernelBuilder()
    .WithAzureChatCompletionService("chat", "...", "...")
    .Build();

var casePlugin = await kernel.ImportChatGptPluginSkillFromUrlAsync("CasePlugin", new Uri("..."));

var planner = new SequentialPlanner(kernel);
var question = "Get me a list of cases and present names as a list. Do not use HTML.";
var plan = await planner.CreatePlanAsync(question);
var result = await plan.InvokeAsync();
```
Available functions:
```
CasePlugin.CreateCase:
  description: Creates new case
  inputs:
    - server_url: server-url (default value: ...)
  - payload: The case to be created (required)
  - content_type: Content type of REST API request body.

CasePlugin.GetAll:
  description: Get all cases
  inputs:
    - server_url: server-url (default value: ...)
```

Created plan:
```
<plan>
    <!-- Get all cases -->
    <function.CasePlugin.GetAll server_url="my-url" setContextVariable="CASES"/>
    <!-- Extract case names from the response -->
    <function.XML.ExtractValue input="$CASES" xpath="//case/name" setContextVariable="CASE_NAMES"/>
    <!-- Format case names as a list -->
    <function.String.Join input="$CASE_NAMES" delimiter=", " setContextVariable="CASE_NAMES_LIST"/>
    <!-- Output case names list -->
    <function.LogMessage message="Case names: $CASE_NAMES_LIST" />
</plan>
```

**Expected behavior**
There is no exception while calling `CreatePlanAsync`

**Screenshots**
N/A

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 2022
 - Language: C#
 - Source: 0.18.230725.3-preview

**Additional context**
N/A
