### ISSUE TITLE
Python: recall method in StepwisePlan not using context

### ISSUE THREAD

**Issue by tarockey** [microsoft/semantic-kernel#3237]
**Describe the bug**
When using the StepwisePlanner, context is not being passed to skills. This is manifesting when using the `recall` ability of the TextMemorySkill in a skill's prompt, always using the default settings (e.g. collection name, limits, etc.). This means that skills cannot be context-dependent.

**To Reproduce**
1. Create a new Kernel, register the TextMemorySkill, and a memory store (currently tested with Azure Cognitive Search as memory store)
2. Create a skill which uses the {{recall}} method inside the prompt template, and register to the kernel.
3. Define a new context with the name of your ACS index as the COLLECTION_PARAM for TextMemorySkill (as shown below):
```python
context = kernel.create_new_context()
context[sk.core_skills.TextMemorySkill.COLLECTION_PARAM] = memory_collection_name
context[sk.core_skills.TextMemorySkill.RELEVANCE_PARAM] = 0.5
context[sk.core_skills.TextMemorySkill.LIMIT_PARAM] = 5
```
4. Create a new SequentialPlanner, passing in your kernel, and a question as the goal.
5. Invoke(`invoke_async`) your plan, passing in the context and memory as parameters:
```python
result = await plan.invoke_async(context=context, memory=kernel.memory)
```
6. Review results, noting that if your ACS index is not named "generic", it will fail to retrieve the relevant memories.
7. Enumerate through the plan._steps, and note the outputs. You will likely see the error
```
Error occurred: Function `recall` execution failed. ResourceNotFoundError: () The index 'generic' for service 'YOUR ACS INDEX' was not found.
```

**Expected behavior**
The recall function should have been passed the correct collection (index) name, and returned relevant memories for the prompt to use as additional context.

**Platform**
 - OS:Windows 11
 - IDE: VS Code
 - Language: Python
 - Source: pip package version 0.3.13.dev0

**Additional Info**

Full repro code below:

```python
import semantic_kernel as sk
from dotenv import load_dotenv
from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion, AzureTextEmbedding
from requests import get
import json
import os
from Plugins.HAPlugin.Homeassistant import HomeAssistant
from semantic_kernel.planning import StepwisePlanner
from semantic_kernel.planning.stepwise_planner.stepwise_planner_config import (
    StepwisePlannerConfig,
)
from semantic_kernel.connectors.memory.azure_cognitive_search import AzureCognitiveSearchMemoryStore

load_dotenv()

kernel = sk.Kernel()

deployment, api_key, endpoint = sk.azure_openai_settings_from_dot_env()

kernel.add_chat_service("chat_completion", AzureChatCompletion(deployment, endpoint, api_key))
intentskills = kernel.import_semantic_skill_from_directory("./skills", 'IntentDetectionSkill')
kernel.add_text_embedding_generation_service("embedding", AzureTextEmbedding("embedding", endpoint, api_key))

kernel.register_memory_store(memory_store=AzureCognitiveSearchMemoryStore(search_endpoint=os.environ.get('AZURE_COGNITIVE_SEARCH_URL'), admin_key=os.environ.get("AZURE_COGNITIVE_SEARCH_APIKEY"), vector_size=1536))

memory_collection_name = 'hadocs'
kernel.import_skill(sk.core_skills.TextMemorySkill())

ask = "Can HomeAssistant split energy usage by Tarriff?"

planner = StepwisePlanner(
    kernel, StepwisePlannerConfig(max_iterations=10, min_iteration_time_ms=1000)
)

plan = planner.create_plan(goal=ask)

context = kernel.create_new_context()
context[sk.core_skills.TextMemorySkill.COLLECTION_PARAM] = memory_collection_name
context[sk.core_skills.TextMemorySkill.RELEVANCE_PARAM] = 0.5
context[sk.core_skills.TextMemorySkill.LIMIT_PARAM] = 5

result = await plan.invoke_async(context=context, memory=kernel.memory)
print(result)

for index, step in enumerate(plan._steps):
    print("Step:", index)
    print("Description:",step.description)
    print("Function:", step.skill_name + "." + step._function.name)
    if len(step._outputs) > 0:
        print( "  Output:\n", str.replace(result[step._outputs[0]],"\n", "\n  "))
```
Sample config.json
```json

{
    "schema": 1,
    "description": "Answer questions related to the home automation system based on documentation",
    "type": "completion",
    "completion": {
      "max_tokens": 100,
      "temperature": 0.1,
      "top_p": 1.0,
      "presence_penalty": 0.0,
      "frequency_penalty": 0.0
    }
  }

```

skprompt.txt
```
If a user has a DocsQuestion, answer the question to the best of your ability using the memory context provided to you.
You are to be helpful and polite. If your memory does not have a relevant answer, do not make up an answer, instead say "I don't know".

context: {{recall $input}}

Please cite your answers with the description property of the memory, and the additional_metadata (listed as "headers")

For example:

Question: Which rasbperry pi hats work with z-wave?

Answer:     - Aeotec Z-Pi 7 Raspberry Pi HAT/Shield (ZWA025, 700 series)
            - Z-Wave.Me RaZberry 7 (ZME_RAZBERRY7, 700 series)
            - Z-Wave.Me RaZberry 7 Pro (ZMEERAZBERRY7_PRO or ZMEURAZBERRY7_PRO, 700 series)
            - Z-Wave.Me Razberry 2 (500 series)"

            source: "Extended instructions how to setup Z-Wave."
            headers: ["## Supported Z-Wave USB Sticks & Hardware Modules"]

Question: How do I edit my configuration.yaml file?

Answer: The easiest option to edit `configuration.yaml` is to use the {% my supervisor_addon title="Studio Code Server add-on" addon="a0d7b954_vscode" %}.
        
            source: "Configuring Home Assistant via text files."
            headers: ["Editing `configuration.yaml`"]


Question: {{$input}}

Answer:
```
