### ISSUE TITLE
.Net: Stackoverflow when using execution settings with YAML format

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3983]
When the following exeuction settings are added, the following stackoverflow occurs

```yaml
name: GenerateStory
template: |
  Tell a story about {{topic}} that is {{length}} sentences long.
template_format: handlebars
description: A function that generates a story about a topic.
input_variables:
  - name: topic
    description: The topic of the story.
    is_required: true
  - name: length
    description: The number of sentences in the story.
    is_required: true
output_variable:
  description: The generated story.
execution_settings:
  - model_id: gpt-4
    temperature: 0.6
  - model_id: gpt-3
    temperature: 0.3
```

<img width="999" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1409190/99ac41b1-d8d6-4f74-8cb3-71450cce5cee">
