### ISSUE TITLE
.Net: Setting json_object mode in execution_settings does not enable JSON mode as expected

### ISSUE THREAD

**Issue by sugii-norichika-intern-fixer** [microsoft/semantic-kernel#4719]
**Describe the bug**
Even if I write `response_format: json_object` in `execution_settings` when defining a Function, the value of the `ResponseFormat` property of `ChatCompletionsOptions` that is sent in the request to OpenAI is null, and JSON mode is not enabled.

**To Reproduce**
1. Create a Function that does not include the word “JSON” in the prompt.
2. Add `response_format: json_object` to `execution_settings`
3. Execute the Function
4. Check if an error occurs

This is the code
```
using StreamReader reader = new(Assembly.GetExecutingAssembly().GetManifestResourceStream(“Simple.prompt.yaml”)!);
// Create prompt
KernelFunction function = kernel.CreateFunctionFromPromptYaml(
    reader.ReadToEnd(),
    promptTemplateFactory: new HandlebarsPromptTemplateFactory()
);
Console.WriteLine(await kernel.InvokeAsync(function))
```
and this is Simple.prompt.yaml
```
name: SimpleResponse
description:  A simple function to respond to the user
template:
    <message role =“”system”“>You are a helpful AI assistant</message>
    <message role =“”user”“>tell me about AI</message>
template_format: handlebars
execution_settings:
    gpt-4-turbo:
        model_id:       gpt-4-turbo
        response_format: json_object
```
**Expected behavior**
The prompt does not include the word "JSON", so if JSON mode is enabled, I should get an error.

Expected error
```
 “error”: {
    “message”: “‘messages’ must contain the word ‘json’ in some form, to use ‘response_format’ of type ‘json_object’.“,
    “type”: “invalid_request_error”,
    “param”: “messages”,
    “code”: null
  }
```
> Documantation
> [https://platform.openai.com/docs/guides/text-generation/json-mode](https://platform.openai.com/docs/guides/text-generation/json-mode)

**Analysis**
On runtime, I have changed the value of `executionSettings.ResponseFormat` used in `ClientCore` line 763 as shown below. Making this change resulted in the expected error, confirming that JSON mode was enabled.

|        | Name                              | Value                              | Type                                    |
| ------ | :-------------------------------: | :--------------------------------: | :-------------------------------------: |
| Before | executionSettings.ResponseFormat	 | ValueKind = String : "json_object" | object { System.Text.Json.JsonElement } |
| After  | executionSettings.ResponseFormat	 | "json_object"	                     | object{string}                          |

The value of `executionSettings` used here comes from `FromExecutionSettings()` in `OpenAIPromptExecutionSettings` line 158. In that function, the value of `OpenAIExecutionSettings` are prepared as follows.
```
var json = JsonSerializer.Serialize(executionSettings);
var openAIExecutionSettings = JsonSerializer.Deserialize<OpenAIPromptExecutionSettings>(json, JsonOptionsCache.ReadPermissive);
```
`OpenAIPromptExecutionSettings.ResponseFormat` is defined as follows, and since it is an `object?` type definition, when `JsonSerializer.Deserialize<OpenAIPromptExecutionSettings>()` is executed, the value is stored as a JsonElement type.
```
public object? ResponseFormat { get; set; }
```
**Platform**
- OS: Windows 10
- IDE: Visual Studio
- Language: C#
- Source: 1.1.0 (nuget)

**Additional context**
- LLM: Azure OpenAI
- Version: GPT-4-Turbo-Preview 1106
