### ISSUE TITLE
PromptExecutionSettings with set ToolCallBehavior to AutoInvokeKernelFunction not working for prompt when RenderAsync is invoked

### ISSUE THREAD

**Issue by Xyloto91** [microsoft/semantic-kernel#5108]
I have prompt in yaml file like this:

```
name: chat conversation
template: |
    **Conversation history**
    {{ ConversationSummaryPlugin.SummarizeConversation $history }}

    User: {{ $request }}
    Assistant:
template_format: semantic-kernel
description: Response on question based on conversation history.
input_variables:
    - name: $history
      description: History of previous conversation
      is_required: true
    - name: $request
      description: Improve this text part from outreach message.
      is_required: true
```

Code:

```
var arguments = new KernelArguments(new OpenAIPromptExecutionSettings { ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions })
{
    { "history", history },
    { "request", request}
};

var promptFileContents = await File.ReadAllTextAsync(promptFilePath);

var promptTemplateConfig = KernelFunctionYaml.ToPromptTemplateConfig(promptFileContents);

var factory = new KernelPromptTemplateFactory();

var promptTemplate = factory.Create(promptTemplateConfig);

var prompt = await promptTemplate.RenderAsync(_kernel, arguments);
```

when I invoke RenderAsync it throws me exception:

The plugin collection does not contain a plugin and/or function with the specified names. Plugin name - 'ConversationSummaryPlugin', function name - 'SummarizeConversation'.
