### ISSUE TITLE
Python: is_required property doesn't throw error if set to true and isn't passed in

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6188]
### Discussed in https://github.com/microsoft/semantic-kernel/discussions/6103

<div type='discussions-op-text'>

<sup>Originally posted by **MaxiPigna** May  2, 2024</sup>
I implemented a simple (Auto) Function Calling kernel.
```
var yamlPrompt = EmbeddedResource.Read("SomePrompt.yml");
var function = kernel.CreateFunctionFromPromptYaml(yamlPrompt, new HandlebarsPromptTemplateFactory());
var args = new KernelArguments(new OpenAIPromptExecutionSettings()
{
    ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions,
})
{
    { "history", chatHistory }
};


var chatResponse = await kernel.InvokeAsync(function, args, cancellationToken);
```

with this Yaml prompt
```
name: SomePrompt
template: |
  Reply to user question.
  Search on {{knowledgeType}} knowledge
  Conversation:
  {{#each history}}
    <message role="{{role}}">{{content}}</message>
  {{/each}}
template_format: handlebars
description: A function that replies to user questions.
input_variables:
  - name: history
    description: conversation history
    is_required: true
  - name: knowledgeType
    description: type of knowledge that could be internal or external
    is_required: true
output_variable:
  description: Answer to question of the user
execution_settings:
  default:
    temperature: 0.1
```
Considering that `knowledgeType` is just an example, since `is_required` is true and I didn't provide the value in the kernel arguments, what is the expected behavior? Because, now it simply ignores it, so I don't understand what is the difference between `is_required` true and false. Thanks.</div>
