### ISSUE TITLE
Python: Support Injecting Chat History into YAML Prompts.

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#6768]

**Comment by eavanvalkenburg** [comment]
I think we already have this, but can you explain a bit more what this entails?

**Comment by moonbox3** [comment]
@alliscode for some more context, Python currently supports:

```yaml
name: getTimeInCity
description: Gets the time in a specified city.
template: |
  Can you help me tell the time in {{$city}} right now?

  {{$chat_history}}
template_format: semantic-kernel
input_variables:
  - name: city
    description: City for which time is desired
    default: Seattle
```

This would render the current `chat_history` as part of the prompt.
